--MOSTRANDO LOS DIFERENTES EJEMPLARES CON SU NOMBRE, EDITORIAL, FECHA DE PUBLICACION, GENERO, AUTOR, COLECCION A LA QUE PERTENECE, TIPO DE COLECCION
-- Y SU IDENTIFICADOR CON RESPECTIVO CODIGO.
SELECT E.NOMBRE, ED.EDITORIAL,E.FECHA_PUBLICACION AS 'FECHA DE PUBLICACION', D.DISPONIBLE, GEN.NOMBRE AS 'GENERO', A.NOMBRE AS 'AUTOR',
CO.NOMBRE AS 'COLECCION', TC.NOMBRE AS 'TIPO', IB.TIPO AS 'IDENTIFICADOR', IB.IDENTIFICADOR AS 'CODIGO', I.IDIOMA
FROM EJEMPLAR E
INNER JOIN  EDITORIAL ED
ON E.id_editorial = ED.id
INNER JOIN DISPONIBILIDAD_EJEMPLAR D
ON E.id_disponibilidad_ejemplar = D.id
INNER JOIN COLECCION CO
ON E.id_coleccion = CO.id
INNER JOIN TIPO_COLECCION TC
ON TC.id= CO.id_tipo
INNER JOIN GENERO GEN
ON CO.id_genero = GEN.id
INNER JOIN AUTOR A
ON E.id_autor = A.id
INNER JOIN ID_BIBLIOGRAFICO IB
ON  E.id_bibliogRafico = IB.id
INNER JOIN IDIOMA I
ON E.id_idioma = I.id
WHERE CO.id = E.id_coleccion 
--GROUP BY E.NOMBRE, ED.EDITORIAL,E.FECHA_PUBLICACION, D.DISPONIBLE, GEN.NOMBRE , A.NOMBRE, CO.NOMBRE, TC.NOMBRE, IB.TIPO, IB.IDENTIFICADOR , I.IDIOMA
ORDER BY E.NOMBRE ASC;

--MOSTRAR LOS USUARIOS QUE PRIMERO RESERVARON EL EJEMPLAR Y LUEGO LHICIERON EL PRESTAMO, TUVIERON QUE HABER MOSTRADO SU NOMBRE, CORREO , FOTO, DIRECCION , OCUPACION  E INSTITUCION PARA HACER ESO Y SE MUESTRA CUALES EL ROL QUE TIENEN, SI SON USUARIOS O SON ADMINISTRADORES.
SELECT U.NOMBRE, U.EMAIL, U.FOTO, U.DIRECCION, U.OCUPACION, U.INSTITUCION, R.ROL, T.TELEFONO, U.cod_qr AS ' CODIGO QR', E.NOMBRE AS 'EJEMPLAR RESERVADO', 
RE.FECHA_RESERVA AS 'RESERVA DE EJEMPLAR', RE.FECHA_DEVOLUCION AS 'SUPUESTA FECHA DE DEVOLUCION', E.NOMBRE AS 'EJEMPLAR PRESTADO', PE.fecha_prestamo AS 'PRESTAMO DE EJEMPLAR',
PE.FECHA_DEVOLUCION AS 'DEVOLUCION DE EJEMPLAR' 
FROM USUARIO U
LEFT JOIN ROL R
ON U.id_rol_usuario = R.id
LEFT JOIN RESERVA_EJEMPLAR RE
ON U.id = re.id_usuario
LEFT JOIN EJEMPLAR E
ON RE.id_ejemplar = E.id
LEFT JOIN TELEFONO T
ON U.id_telefono = T.id
LEFT JOIN PRESTAMO_EJEMPLAR PE
ON U.id = PE.id_ejemplar
--WHERE E.id = PE.id_ejemplar
ORDER BY U.nombre DESC;


--MOSTRAR EVENTOS, EL AREA DONDE HAN SIDO LOS EVENTOS, LA FECHA




SELECT * FROM EJEMPLAR
SELECT*FROM COLECCION;
SELECT*FROM TIPO_COLECCION;
SELECT*FROM ID_BIBLIOGRAFICO;
SELECT*FROM USUARIO;
SELECT id_usuario FROM RESERVA_EJEMPLAR;
SELECT*FROM EVENTO;
SELECT * FROM OBJETIVO_EVENTO;