--MOSTRANDO LOS DIFERENTES EJEMPLARES CON SU NOMBRE, EDITORIAL, FECHA DE PUBLICACION, GENERO, AUTOR, COLECCION A LA QUE PERTENECE, TIPO DE COLECCION
-- Y SU IDENTIFICADOR CON RESPECTIVO CODIGO.
SELECT E.NOMBRE, ED.EDITORIAL,E.FECHA_PUBLICACION AS 'FECHA DE PUBLICACION', D.DISPONIBLE, GEN.NOMBRE AS 'GENERO', A.NOMBRE AS 'AUTOR',
CO.NOMBRE AS 'COLECCION', TC.NOMBRE AS 'TIPO', IB.TIPO AS 'IDENTIFICADOR', IB.IDENTIFICADOR AS 'CODIGO', I.IDIOMA
FROM EJEMPLAR E
INNER JOIN  EDITORIAL ED
ON E.id_editorial = ED.id
INNER JOIN DISPONIBILIDAD_EJEMPLAR D
ON E.id_disponibilidad_ejemplar = D.id
INNER JOIN COLECCION CO
ON E.id_coleccion = CO.id
INNER JOIN TIPO_COLECCION TC
ON TC.id= CO.id_tipo
INNER JOIN GENERO GEN
ON CO.id_genero = GEN.id
INNER JOIN AUTOR A
ON E.id_autor = A.id
INNER JOIN ID_BIBLIOGRAFICO IB
ON  E.id_bibliogRafico = IB.id
INNER JOIN IDIOMA I
ON E.id_idioma = I.id
WHERE CO.id = E.id_coleccion 
--GROUP BY E.NOMBRE, ED.EDITORIAL,E.FECHA_PUBLICACION, D.DISPONIBLE, GEN.NOMBRE , A.NOMBRE, CO.NOMBRE, TC.NOMBRE, IB.TIPO, IB.IDENTIFICADOR , I.IDIOMA
ORDER BY E.NOMBRE ASC;

--MOSTRAR LOS USUARIOS QUE PRIMERO RESERVARON EL EJEMPLAR Y LUEGO LHICIERON EL PRESTAMO, FORMATO DEL EJEMPLAR,  EL ROL QUE TIENEN(SI SON USUARIOS O SON ADMINISTRADORES).
SELECT U.NOMBRE, U.EMAIL, R.ROL, F.FORMATO, U.cod_qr AS ' CODIGO QR', E.NOMBRE AS 'EJEMPLAR RESERVADO', 
RE.FECHA_RESERVA AS 'RESERVA DE EJEMPLAR', RE.FECHA_DEVOLUCION AS 'SUPUESTA FECHA DE DEVOLUCION', E.NOMBRE AS 'EJEMPLAR PRESTADO', PE.fecha_prestamo AS 'PRESTAMO DE EJEMPLAR',
PE.FECHA_DEVOLUCION AS 'DEVOLUCION DE EJEMPLAR' 
FROM USUARIO U
LEFT JOIN ROL R
ON U.id_rol_usuario = R.id
LEFT JOIN RESERVA_EJEMPLAR RE
ON U.id = re.id_usuario
LEFT JOIN EJEMPLAR E
ON RE.id_ejemplar = E.id
INNER JOIN FORMATO F
ON E.id_formato = F.id
LEFT JOIN PRESTAMO_EJEMPLAR PE
ON U.id = PE.id_ejemplar
--WHERE E.id = PE.id_ejemplar
ORDER BY U.nombre DESC;


--MOSTRAR EVENTOS, EL AREA DONDE HAN SIDO LOS EVENTOS, LA FECHA
SELECT EV.TITULO, OB.objetivo AS 'OBJETIVO DEL EVENTO', A.fecha_final AS 'FECHA DE INICIO', A.fecha_final AS 'FECHA DE FINALIZACION', U.NOMBRE 'VISITANTES'/*, COUNT(U.ID) 'CONTANDO'*/, ASI.fecha_entrada AS 'ENTRO A',
ASI.fecha_salida AS 'SALIO A', AR.NOMBRE AS ' AREA DONDE SE REALIZA EL EVENTO'
FROM EVENTO EV
INNER JOIN ACTIVIDAD A
ON EV.id= A.id_evento
INNER JOIN USUARIO U
ON U.id = A.id_usuario
INNER JOIN OBJETIVO_EVENTO OB
ON EV.id = OB.id_evento
FULL OUTER JOIN ASISTENCIA ASI
ON A.id = ASI.id_actividad
INNER JOIN AREA AR
ON A.id_area= AR.id
WHERE A.id_evento= EV.id
GROUP BY U.NOMBRE, ev.titulo, A.fecha_final,a.fecha_inicio, ASI.fecha_entrada, ASI.fecha_salida, OB.objetivo, AR.nombre
ORDER BY EV.titulo  ASC;

--MOSTRAR AREA CON SU RESPECTIVO RESPONSABLE, SI ESTA DISPONIBLE O NO, SU HORARIO 
SELECT A.NOMBRE, A.DESCRIPCION, A.PISO, H.DIAS AS ' DIAS ABIERTO', H.HORAS AS 'HORAS ABIERTO', R.NOMBRE 'RESPONSABLE DEL AREA',
D.DISPONIBLE AS 'DISPONIBILIDAD DE AREA'
FROM AREA A
INNER JOIN HORARIO H
ON A.id_horario = H.id
INNER JOIN RESPONSABLE R
ON A.id_responsable = R.id
INNER JOIN DISPONIBILIDAD_AREA D
ON A.id_disponibilidad_area = D.id
ORDER BY A.NOMBRE ASC;


--MOSTRANDO  A LOS ADMINISTRADORES
SELECT  r.rol AS 'ROL', U.NOMBRE, U.email AS 'CORREO ELECTRONICO', U.DIRECCION, U.OCUPACION, U.INSTITUCION, T.TELEFONO, U.FOTO, U.cod_qr AS ' CODIGO QR', U.password_user AS 'CONTRASEÑA'
FROM USUARIO U
INNER JOIN TELEFONO T
ON U.id_telefono = T.id
INNER JOIN ROL R
ON U.id_rol_usuario = R.id
WHERE U.id_rol_usuario = 1
ORDER BY U.nombre DESC;

--MOSTRANDO A LOS USUARIOS
SELECT  r.rol AS 'ROL', U.NOMBRE, U.email AS 'CORREO ELECTRONICO', U.DIRECCION, U.OCUPACION, U.INSTITUCION, T.TELEFONO, U.FOTO, U.cod_qr AS ' CODIGO QR', U.password_user AS 'CONTRASEÑA'
FROM USUARIO U
INNER JOIN TELEFONO T
ON U.id_telefono = T.id
INNER JOIN ROL R
ON U.id_rol_usuario = R.id
WHERE U.id_rol_usuario = 2
ORDER BY U.nombre DESC;



SELECT * FROM ROL
SELECT * FROM EJEMPLAR
SELECT*FROM COLECCION;
SELECT*FROM TIPO_COLECCION;
SELECT*FROM ID_BIBLIOGRAFICO;
SELECT*FROM USUARIO;
SELECT id_usuario FROM RESERVA_EJEMPLAR;
SELECT*FROM EVENTO;
SELECT * FROM OBJETIVO_EVENTO;
SELECT *FROM ACTIVIDAD;
select*from ASISTENCIA
SELECT*FROM  GENERO;
SELECT*FROM  AUTOR;
SELECT*FROM  HORARIO;
select * from  DISPONIBILIDAD_EJEMPLAR;